export default [{
  "label": "北区",
  "value": "100",
  "children": [{
    "label": "桔园",
    "value": "101",
  }, {
    "label": "桃园",
    "value": "102",
  }, {
    "label": "李园",
    "value": "103",
  }, {
    "label": "榴园",
    "value": "104",
  }, {
    "label": "枣园",
    "value": "105",
  }, {
    "label": "杏园",
    "value": "106",
  }, {
    "label": "榴园",
    "value": "107",
  }, {
    "label": "蕙园",
    "value": "108",
  }, {
    "label": "博学北楼",
    "value": "109",
  }, {
    "label": "理工楼",
    "value": "110",
  }, {
    "label": "物质科学研究院",
    "value": "111",
  }, {
    "label": "行知楼",
    "value": "112",
  }, {
    "label": "笃行北楼",
    "value": "201",
  }],
  "label": "南区",
  "value": "200",
  "children": [{
    "label": "松园",
    "value": "201",
  }, {
    "label": "梅园",
    "value": "202",
  }, {
    "label": "竹园",
    "value": "203",
  }, {
    "label": "桂园",
    "value": "204",
  }, {
    "label": "槐园",
    "value": "205",
  }, {
    "label": "枫园",
    "value": "206",
  }, {
    "label": "松园",
    "value": "207",
  }, {
    "label": "行政楼",
    "value": "208",
  }, {
    "label": "社科楼",
    "value": "209",
  }, {
    "label": "博学南楼",
    "value": "210",
  }, {
    "label": "笃行南楼",
    "value": "211",
  }],
  "label": "大学生活动中心",
  "value": "300",
  "children": [],
  "label": "文典阁",
  "value": "400",
  "children": [],
}]